import pandas as pd
import pytest

from dna_fractal.genome import align, arms, ibs, mendelian_errors, read_23andme

RAW = """\
# This data file generated by 23andMe
# rsid\tchromosome\tposition\tgenotype
rs3\t1\t300\tAG
rs1\t1\t100\tAA
rs2\t1\t200000000\t--
rs4\tX\t50\tA
rs5\tMT\t60\tG
"""


@pytest.fixture
def raw_file(tmp_path):
    path = tmp_path / "genome.txt"
    path.write_text(RAW)
    return path


def test_read_keeps_file_order_and_calls(raw_file):
    df = read_23andme(raw_file)
    assert list(df["rsid"]) == ["rs3", "rs1", "rs2", "rs4", "rs5"]
    assert list(df["genotype"]) == ["AG", "AA", "--", "A", "G"]
    assert list(df["chromosome"].cat.categories[-3:]) == ["X", "Y", "MT"]


def test_read_accepts_an_uncommented_header(tmp_path):
    path = tmp_path / "edited.txt"
    path.write_text("rsid\tchromosome\tposition\tgenotype\nrs1\t1\t100\tAA\n")
    df = read_23andme(path)
    assert list(df["rsid"]) == ["rs1"]
    assert df["position"].dtype == "int64"


def test_arms_split_at_the_centromere_and_sort_by_position(raw_file):
    p, q = arms(read_23andme(raw_file), "1")
    assert list(p["rsid"]) == ["rs1", "rs3"]
    assert list(q["rsid"]) == ["rs2"]


@pytest.mark.parametrize(
    ("a", "b", "shared"),
    [("AA", "AA", 2), ("AG", "GA", 2), ("AG", "AA", 1), ("AA", "GG", 0), ("AG", "CT", 0),
     ("AA", "--", None), ("A", "A", None)],
)  # fmt: skip
def test_ibs(a, b, shared):
    result = ibs(pd.Series([a]), pd.Series([b]))[0]
    assert (result is pd.NA) if shared is None else (result == shared)


def test_mendelian_errors():
    child = pd.Series(["AG", "GG", "AA", "AG"])
    father = pd.Series(["AA", "AA", "AG", "--"])
    mother = pd.Series(["GG", "AG", "AG", "AA"])
    result = mendelian_errors(child, father, mother)
    assert list(result[:3]) == [False, True, False]
    assert result[3] is pd.NA


def test_align_keeps_shared_snps_in_position_order(tmp_path):
    a = tmp_path / "a.txt"
    b = tmp_path / "b.txt"
    a.write_text("rs1\t1\t20\tAA\nrs2\t1\t10\tAG\nrs3\t1\t30\tGG\n")
    b.write_text("rs2\t1\t10\tGG\nrs1\t1\t20\tAA\n")
    table = align({"a": read_23andme(a), "b": read_23andme(b)}, "1")
    assert list(table.index) == ["rs2", "rs1"]
    assert list(table.columns) == ["position", "a", "b"]
