name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: uv sync
      - run: uv run ruff check
      - run: uv run ruff format --check
      - run: uv run pytest
      - uses: actions/cache@v4
        with:
          path: data
          key: corpasome-v1
      - run: uv run pytest --nbmake notebooks
